name: 【Docker】 Build and Push Docker image
on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches: [ "main" ]
    paths: [ "Dockerfile",".github/workflows/docker-build-publish.yml","web/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Dockerfile",".github/workflows/docker-build-publish.yml","web/**" ]
  workflow_dispatch: ~

jobs:
  Build_Docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3.2.1
      with:
        path: /tmp/.buildx-cache
        key: donate-${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          donate-${{ runner.os }}-buildx-
          
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/donate
        tags: |
          type=raw,value=latest,enable=true
        labels: |
          org.opencontainers.image.author=KIMI360
          org.opencontainers.image.description=
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.source=https://github.com/kimi360/Docker-Donate
          org.opencontainers.image.title=${{ secrets.DOCKER_USERNAME }}/donate
          org.opencontainers.image.url=https://github.com/kimi360/Docker-Donate
          org.opencontainers.image.version=
          org.opencontainers.image.docker.cmd=docker run -p 80:80 -d kimi360/donate
        flavor: latest=false     

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
